export const data = [
  {
    _id: "EVT0001",
    location: "Bangalore",
    gender: "Female",
    name: "Female01",
    time: "5-Jan-23",
    date: "9:05:23",
    image: "/images/Female01.jpg",
  },
  {
    _id: "EVT0002",
    location: "Chennai",
    gender: "Male",
    name: "Male01",
    time: "5-Jan-23",
    date: "9:11:03",
    image: "/images/Male01.jpg",
  },
  {
    _id: "EVT0003",
    location: "Bangalore",
    gender: "Male",
    name: "Male02",
    time: "5-Jan-23",
    date: "10:04:05",
    image: "/images/Male02.jpg",
  },
  {
    _id: "EVT0004",
    location: "Bangalore",
    gender: "Female",
    name: "Female02",
    time: "5-Jan-23",
    date: "10:39:09",
    image: "/images/Female02.jpg",
  },
  {
    _id: "EVT0005",
    location: "Chennai",
    gender: "Female",
    name: "Female03",
    time: "5-Jan-23",
    date: "11:14:13",
    image: "/images/Female03.jpg",
  },
  {
    _id: "EVT0006",
    location: "Bangalore",
    gender: "Male",
    name: "Male03",
    time: "5-Jan-23",
    date: "11:49:17",
    image: "/images/Male03.jpg",
  },
  {
    _id: "EVT0007",
    location: "Hyderabad",
    gender: "Female",
    name: "Female04",
    time: "5-Jan-23",
    date: "12:24:21",
    image: "/images/Female04.jpg",
  },
  {
    _id: "EVT0008",
    location: "Hyderabad",
    gender: "Male",
    name: "Male04",
    time: "5-Jan-23",
    date: "12:59:25",
    image: "/images/Male04.jpg",
  },
  {
    _id: "EVT0009",
    location: "Chennai",
    gender: "Male",
    name: "Male05",
    time: "5-Jan-23",
    date: "13:34:29",
    image: "/images/Male05.jpg",
  },
  {
    _id: "EVT0010",
    location: "Hyderabad",
    gender: "Female",
    name: "Female05",
    time: "5-Jan-23",
    date: "14:09:33",
    image: "/images/Female05.jpg",
  },
  {
    _id: "EVT0011",
    location: "Bangalore",
    gender: "Male",
    name: "Male06",
    time: "5-Jan-23",
    date: "14:44:37",
    image: "/images/Male06.jpg",
  },
  {
    _id: "EVT0012",
    location: "Hyderabad",
    gender: "Male",
    name: "Male07",
    time: "5-Jan-23",
    date: "15:19:41",
    image: "/images/Male07.jpg",
  },
  {
    _id: "EVT0013",
    location: "Chennai",
    gender: "Female",
    name: "Female06",
    time: "5-Jan-23",
    date: "15:54:45",
    image: "/images/Female06.jpg",
  },
  {
    _id: "EVT0014",
    location: "Chennai",
    gender: "Female",
    name: "Female07",
    time: "5-Jan-23",
    date: "16:29:49",
    image: "/images/Female07.jpg",
  },
  {
    _id: "EVT0015",
    location: "Bangalore",
    gender: "Female",
    name: "Female08",
    time: "6-Jan-23",
    date: "17:04:53",
    image: "/images/Female08.jpg",
  },
  {
    _id: "EVT0016",
    location: "Chennai",
    gender: "Male",
    name: "Male08",
    time: "6-Jan-23",
    date: "17:39:57",
    image: "/images/Male08.jpg",
  },
  {
    _id: "EVT0017",
    location: "Chennai",
    gender: "Male",
    name: "Male09",
    time: "6-Jan-23",
    date: "18:15:01",
    image: "/images/Male09.jpg",
  },
  {
    _id: "EVT0018",
    location: "Bangalore",
    gender: "Female",
    name: "Female09",
    time: "6-Jan-23",
    date: "18:50:05",
    image: "/images/Female09.jpg",
  },
  {
    _id: "EVT0019",
    location: "Bangalore",
    gender: "Female",
    name: "Female10",
    time: "6-Jan-23",
    date: "19:25:09",
    image: "/images/Female10.jpg",
  },
  {
    _id: "EVT0020",
    location: "Hyderabad",
    gender: "Male",
    name: "Male10",
    time: "6-Jan-23",
    date: "20:00:13",
    image: "/images/Male10.jpg",
  },
  {
    _id: "EVT0021",
    location: "Chennai",
    gender: "Male",
    name: "Male11",
    time: "6-Jan-23",
    date: "20:35:17",
    image: "/images/Male11.jpg",
  },
  {
    _id: "EVT0022",
    location: "Hyderabad",
    gender: "Female",
    name: "Female11",
    time: "6-Jan-23",
    date: "21:10:21",
    image: "/images/Female11.jpg",
  },
  {
    _id: "EVT0023",
    location: "Hyderabad",
    gender: "Male",
    name: "Male12",
    time: "6-Jan-23",
    date: "21:45:25",
    image: "/images/Male12.jpg",
  },
  {
    _id: "EVT0024",
    location: "Bangalore",
    gender: "Female",
    name: "Female12",
    time: "6-Jan-23",
    date: "22:20:29",
    image: "/images/Female12.jpg",
  },
  {
    _id: "EVT0025",
    location: "Bangalore",
    gender: "Male",
    name: "Male13",
    time: "6-Jan-23",
    date: "22:55:33",
    image: "/images/Male13.jpg",
  },
  {
    _id: "EVT0026",
    location: "Hyderabad",
    gender: "Female",
    name: "Female13",
    time: "6-Jan-23",
    date: "23:30:37",
    image: "/images/Female13.jpg",
  },
  {
    _id: "EVT0027",
    location: "Hyderabad",
    gender: "Male",
    name: "Male14",
    time: "7-Jan-23",
    date: "0:05:41",
    image: "/images/Male14.jpg",
  },
  {
    _id: "EVT0028",
    location: "Hyderabad",
    gender: "Male",
    name: "Male15",
    time: "7-Jan-23",
    date: "0:40:45",
    image: "/images/Male15.jpg",
  },
  {
    _id: "EVT0029",
    location: "Hyderabad",
    gender: "Female",
    name: "Female14",
    time: "7-Jan-23",
    date: "1:15:49",
    image: "/images/Female14.jpg",
  },
  {
    _id: "EVT0030",
    location: "Chennai",
    gender: "Female",
    name: "Female15",
    time: "7-Jan-23",
    date: "1:50:53",
    image: "/images/Female15.jpg",
  },
  {
    _id: "EVT0031",
    location: "Chennai",
    gender: "Female",
    name: "Female16",
    time: "7-Jan-23",
    date: "2:25:57",
    image: "/images/Female16.jpg",
  },
  {
    _id: "EVT0032",
    location: "Chennai",
    gender: "Male",
    name: "Male16",
    time: "7-Jan-23",
    date: "3:01:01",
    image: "/images/Male16.jpg",
  },
  {
    _id: "EVT0033",
    location: "Chennai",
    gender: "Male",
    name: "Male17",
    time: "8-Jan-23",
    date: "3:36:05",
    image: "/images/Male17.jpg",
  },
  {
    _id: "EVT0034",
    location: "Bangalore",
    gender: "Male",
    name: "Male18",
    time: "8-Jan-23",
    date: "4:11:09",
    image: "/images/Male18.jpg",
  },
  {
    _id: "EVT0035",
    location: "Chennai",
    gender: "Male",
    name: "Male19",
    time: "8-Jan-23",
    date: "4:46:13",
    image: "/images/Male19.jpg",
  },
  {
    _id: "EVT0036",
    location: "Bangalore",
    gender: "Female",
    name: "Female17",
    time: "9-Jan-23",
    date: "5:21:17",
    image: "/images/Female17.jpg",
  },
  {
    _id: "EVT0037",
    location: "Hyderabad",
    gender: "Female",
    name: "Female18",
    time: "9-Jan-23",
    date: "5:56:21",
    image: "/images/Female18.jpg",
  },
  {
    _id: "EVT0038",
    location: "Hyderabad",
    gender: "Male",
    name: "Male20",
    time: "9-Jan-23",
    date: "6:31:25",
    image: "/images/Male20.jpg",
  },
  {
    _id: "EVT0039",
    location: "Chennai",
    gender: "Male",
    name: "Male21",
    time: "9-Jan-23",
    date: "7:06:29",
    image: "/images/Male21.jpg",
  },
  {
    _id: "EVT0040",
    location: "Bangalore",
    gender: "Male",
    name: "Male22",
    time: "9-Jan-23",
    date: "7:41:33",
    image: "/images/Male22.jpg",
  },
  {
    _id: "EVT0041",
    location: "Hyderabad",
    gender: "Female",
    name: "Female19",
    time: "9-Jan-23",
    date: "8:16:37",
    image: "/images/Female19.jpg",
  },
  {
    _id: "EVT0042",
    location: "Bangalore",
    gender: "Female",
    name: "Female20",
    time: "9-Jan-23",
    date: "8:51:41",
    image: "/images/Female20.jpg",
  },
  {
    _id: "EVT0043",
    location: "Chennai",
    gender: "Male",
    name: "Male23",
    time: "9-Jan-23",
    date: "9:26:45",
    image: "/images/Male23.jpg",
  },
  {
    _id: "EVT0044",
    location: "Bangalore",
    gender: "Female",
    name: "Female21",
    time: "9-Jan-23",
    date: "10:01:49",
    image: "/images/Female21.jpg",
  },
  {
    _id: "EVT0045",
    location: "Bangalore",
    gender: "Male",
    name: "Male24",
    time: "9-Jan-23",
    date: "10:36:53",
    image: "/images/Male24.jpg",
  },
  {
    _id: "EVT0046",
    location: "Chennai",
    gender: "Female",
    name: "Female22",
    time: "9-Jan-23",
    date: "11:11:57",
    image: "/images/Female22.jpg",
  },
  {
    _id: "EVT0047",
    location: "Chennai",
    gender: "Female",
    name: "Female23",
    time: "9-Jan-23",
    date: "11:47:01",
    image: "/images/Female23.jpg",
  },
  {
    _id: "EVT0048",
    location: "Hyderabad",
    gender: "Male",
    name: "Male25",
    time: "9-Jan-23",
    date: "12:22:05",
    image: "/images/Male25.jpg",
  },
  {
    _id: "EVT0049",
    location: "Hyderabad",
    gender: "Female",
    name: "Female24",
    time: "9-Jan-23",
    date: "12:57:09",
    image: "/images/Female24.jpg",
  },
  {
    _id: "EVT0050",
    location: "Chennai",
    gender: "Female",
    name: "Female25",
    time: "9-Jan-23",
    date: "13:32:13",
    image: "/images/Female25.jpg",
  },
];
